### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export

### ISSUE THREAD

**Issue by jonathon-love** [vite-plugin/vite-plugin-commonjs#15]
hi,

i'm using `vite-plugin-commonjs` with an established project, but what i find is that `require()`s of this form:

```
const { s6e } = require('./utils');
```

produce code which causes the following error:

```
Uncaught SyntaxError: ambiguous indirect export
```

if i change my code to:

```
const utils = require('./utils');
const s6e = utils.s6e;
```

then it works. is there a way `vite-plugin-commonjs` can handle this automatically, or do i need to modify all my code?

with thanks

**Comment by caoxiemeihao** [comment]
Hi! 👋
Can you provide a minimal reproduction Demo? 👀

**Comment by jonathon-love** [comment]
```
<!DOCTYPE html>
<html lang="en">
    <script type="module" src="/main.js"></script>
  </body>
</html>
```

```
// main.js

const { fred } = require('./one');
console.log(fred);
```

```
// one.js

module.exports = { fred: 4, jim: 6 };
```

```
// vite.config.js

import { defineConfig } from 'vite';

import commonjs from 'vite-plugin-commonjs';
import vitePluginRequire from 'vite-plugin-require';

export default defineConfig({
  plugins: [
    // vitePluginRequire.default(),  // transform require()s
    commonjs(),           // transform module.exports
  ],
});
```

then if i start `vite` and navigate to `localhost:5173` i receive the error `ambiguous indirect export: fred`

if i navigate to `localhost:5173/main.js` i see that it has been transformed to:

```
import { fred } from '/one.js';
console.log(fred);
```

which doesn't work ...

HOWEVER, i've since discovered that i can use the `vite-plugin-require` to get this to work:

```
export default defineConfig({
  plugins: [
    vitePluginRequire.default(),  // transform require()s
    commonjs(),           // transform module.exports
  ],
});
```

it transforms the `require()` and commonjs transforms the `module.exports`.

`vite-plugin-require` transforms `main.js` so it looks like:

```
import vitePluginRequire_1668060469992_650 from "/one.js";
const {
  fred
} = (vitePluginRequire_1668060469992_650);
console.log(fred);
```

... and this works!

**Comment by caoxiemeihao** [comment]
I will Debug it :)

**Comment by caoxiemeihao** [comment]
Now, `v0.6.0` is available :)

**Comment by kyle-belle** [comment]
are there any options i need to provide to get this to work? I'm getting this same error currently and i stumbled upon this and tried with the latest version as of now `^0.10.1` but it doesn't work. still get 
`Uncaught SyntaxError: ambiguous indirect export: getErrorMessage`
with this code
```ts
import { getErrorMessage } from "@app/utils";
```

when i change it to
```ts
import * as utils from "@app/utils";
const { getErrorMessage } = utils;
```
the error goes away (from this one at least. still happens in the many other places i try to import like that

**Comment by yejimeiming** [comment]
@kyle-belle can you provide a minimal reproduction repo?

**Comment by kyle-belle** [comment]
The issue isn't with this lib as im not sure it was ever meant to solve my specific issue

i found a way to get my imports to work when importing my other commonJs modules (written in typescript so really the source is more like esm really). since vite doesn't really need the built files i just redirect any request using `import` to use the source files using the package.json `exports` property.
```json
{
  "name": "@app/utils",
  "private": true,
  "version": "1.0.0",
  "description": "App's util functions",
  "main": "build/index.js",
  "exports": {
    ".": {
      "types": "./index.ts",
      "require": "./build/index.js",
      "import": "./index.ts"
    },
    "./src/": {
      "types": "./src/",
      "require": "./build/src/",
      "import": "./src/"
    }
  },
  "scripts": {
    "clean-build": "yarn rimraf build",
    "build": "yarn tsc",
    "watch": "tsc --watch"
   }
}
```

**Comment by yejimeiming** [comment]
> Actually quick question. i now realize im using import rather than require. is it supposed to enable imports to to work with commonJs files or is it just not possible?

Your confusion exists, as `ESM` and `CJS` are not 💯% compatible.
Many times, fixed `module-imterop` can only be used, such as `import * as lib from 'cjs-lib`, even Vite can only do so.

See Vite source code 👉 https://github.com/vitejs/vite/blob/v5.0.2/packages/vite/src/node/plugins/importAnalysis.ts#L915

**Comment by sofer-eg** [comment]
Hi! Got the same errors with this project https://github.com/anse-app/anse
`Uncaught (in promise) SyntaxError: ambiguous indirect export: setProperty [Markdown.tsx:3:10](http://localhost:3002/src/components/Markdown.tsx)
Uncaught (in promise) SyntaxError: ambiguous indirect export: setProperty 2 [SettingsApiKey.tsx:7:10](http://localhost:3002/src/components/ui/SettingsApiKey.tsx)`
