### ISSUE TITLE
[feature request] support "exports = module.exports = {xxx}" syntax

### ISSUE THREAD

**Issue by fifv** [vite-plugin/vite-plugin-commonjs#17]
A lib use this syntax to export, then error occurs.
![image](https://user-images.githubusercontent.com/75289510/205494016-569dc943-95e6-461b-80cb-487b20178d74.png)
![image](https://user-images.githubusercontent.com/75289510/205494021-b8965fc2-97a1-48d8-894b-6131c1aafc0f.png)
This can be fixed by manually changing to `module.exports = {xxx}`, but it would be better that this syntax can be used as is.

This plugin makes my life easier, with thanks.

**Comment by caoxiemeihao** [comment]
👋
Now, you can try use `v0.6.1`.
One thing to note.
https://github.com/vite-plugin/vite-plugin-commonjs/blob/f9328ba69f912f8f040837d1308ca96597b89170/test/src/exports.js#L4-L7

**Comment by fifv** [comment]
It works! Thanks a lot💕
