### ISSUE TITLE
support transform modules under node_modules

### ISSUE THREAD

**Issue by JieamI** [vite-plugin/vite-plugin-commonjs#19]
![image](https://user-images.githubusercontent.com/49944489/224030788-d77b0b76-da6b-4d00-a57b-37a04a7ed89d.png)
Why not leave the choice to the user, but just filter out the modules under node_modules?

**Comment by caoxiemeihao** [comment]
The file in the `node_modules/.vite` dir is a Vite Pre-Bunding file, it shouldn't be processed if it has problems then you should start with `optimizeDeps` to fix it.

**Comment by caoxiemeihao** [comment]
Yes! you are right.
`transform modules under node_modules` introduce a lot of performance overhead, and in theory they are Pre-Bundling by Vite into the `node_modules/.vite` folder, so we should handle the files in the `node_modules/.vite` folder.

However, users who prevent prebuilds of `node_modules` will never be processed.

**Comment by JieamI** [comment]
Currently, I am using vitest, which doesn't have the ability to optimize deps like vite, there is also not `node_modules/.vite`. Moreover, it only supports ESM. so I have to transform some legacy packages in the node_modules.
it would be better if this plugin can support it.

**Comment by caoxiemeihao** [comment]
- [ ] TODO: support `node_modules`

**Comment by JieamI** [comment]
> My be, you can submit a PR for this :)

It's my pleasure and I'll do so this weekend :)
