### ISSUE TITLE
 [vite] Internal server error: Unexpected character '@' (1:0)

### ISSUE THREAD

**Issue by jetBn** [vite-plugin/vite-plugin-commonjs#21]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/26957220/227728189-7cafe791-241f-4b3f-bada-59e9154db55e.png">

**Comment by caoxiemeihao** [comment]
Can your provide a minimal reproduction repo?

**Comment by GBY-1** [comment]
我使用module.exports导出一个对象，并在另一个页面引入该对象的一个键值，而得到的结果是引入了整个对象，不应该是键所对应的值嘛？
My Code content:
utils.js
module.exports ={admin:'super',code:401}
test1.vue
import admin from '@/config'
console.log(admin)

result print {admin:'super',code:401}
Is not print super? @caoxiemeihao

**Comment by caoxiemeihao** [comment]
@GBY-1 `module.exports=xxx` 最终是将 `xxx` 放到 `export default` 上，CommonJS 与 ESModule 的 interoperate 不是完美的
https://github.com/vite-plugin/vite-plugin-commonjs/blob/v0.6.2/src/generate-export.ts#L29

**Comment by GBY-1** [comment]
好的 非常感谢！
