### ISSUE TITLE
Internal server error: str.includes is not a function

### ISSUE THREAD

**Issue by JinZhang-96** [vite-plugin/vite-plugin-commonjs#22]
For example, if commonjs dynamically imports files such as require ('../a/b'+value+'. png'), the above error will be reported。

code position:
424 line at index.js  

const example = "For example: import(`./foo/${bar}.js`).";
function sanitizeString(str) {
  if(typeof str !== undefined){
    str = str+""
  }
  if (str.includes("*")) {
    throw new Error("A dynamic import cannot contain * characters.");
  }
  return str;
}

**Comment by caoxiemeihao** [comment]
Can you provide a minimal reproduction repo?
