### ISSUE TITLE
Breaks when using ??= syntax

### ISSUE THREAD

**Issue by jcbhmr** [vite-plugin/vite-plugin-commonjs#32]
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/33897546-e7cd-47f8-9d7a-23216fb0821d)
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/55b9d350-804b-4dd1-8e80-0c335cdc241c)
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/f48e7608-f1ba-4fdb-9a94-35e850411379)

vs

![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/180cef48-efcc-4e4a-8a69-2307c36bfc29)
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/4d4c9f27-eec5-4be5-ab88-aba7dd430e44)
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/ac149ccd-b129-4154-b2e5-5f193cc00341)

I assume that something about this package breaks when using `??=` syntax?

**Comment by jcbhmr** [comment]
Yeah, it's this:
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/327aa17f-e571-4617-b368-31baa3568cb8)

`??=` is invalid 2020 syntax apparently, so it goes to the `catch {}` block and ignores it; thus leading to there being no exports, and thus leading to a syntax error.

To fix this, I think that all you'd need to do is change 2020 to "latest" or 2023
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/61068799/213a6955-4a3c-47b0-b130-c1c9d9be8a25)

**Comment by jcbhmr** [comment]
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vite-plugin-commonjs/dist/index.js b/node_modules/vite-plugin-commonjs/dist/index.js
index 9e8973b..73ebd5e 100644
--- a/node_modules/vite-plugin-commonjs/dist/index.js
+++ b/node_modules/vite-plugin-commonjs/dist/index.js
@@ -390,7 +390,7 @@ async function transformCommonjs({
     return;
   let ast;
   try {
-    ast = acorn.parse(code, { sourceType: "module", ecmaVersion: 2020 });
+    ast = acorn.parse(code, { sourceType: "module", ecmaVersion: "latest" });
   } catch (error) {
     return null;
   }
diff --git a/node_modules/vite-plugin-commonjs/dist/index.mjs b/node_modules/vite-plugin-commonjs/dist/index.mjs
index faaa42a..586d5d0 100644
--- a/node_modules/vite-plugin-commonjs/dist/index.mjs
+++ b/node_modules/vite-plugin-commonjs/dist/index.mjs
@@ -388,7 +388,7 @@ async function transformCommonjs({
     return;
   let ast;
   try {
-    ast = parse(code, { sourceType: "module", ecmaVersion: 2020 });
+    ast = parse(code, { sourceType: "module", ecmaVersion: "latest" });
   } catch (error) {
     return null;
   }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by caoxiemeihao** [comment]
`acron@7.x` allowed latest `ecamVersion` is `11` or `2020` [see here](https://github.com/acornjs/acorn/blob/7.4.1/acorn/dist/acorn.d.ts#L15), current vite-plugin-commonjs not force use the `acron@8.x`.
Maybe `ecmaVersion: 14` is better, because acron source code use the `>` operate for compare rather than `===`
<img width="591" alt="image" src="https://github.com/vite-plugin/vite-plugin-commonjs/assets/26263658/a0ef962d-2817-43aa-816e-e761d9d067c2">

**Comment by jcbhmr** [comment]
Is there a reason that you aren't using the latest version of acorn? 🤔
