### ISSUE TITLE
ReferenceError: Cannot access 'G0' before initialization

### ISSUE THREAD

**Issue by KolissnikBogdan** [vite-plugin/vite-plugin-commonjs#47]
Hello, first of all I want to thank you for this wonderful package)
I had this problem: "require is not defined vite" (after I created the build). I updated my vite.config by adding: 

```
 commonjs({
      filter(id) {
        // `node_modules` is exclude by default, so we need to include it explicitly
        // https://github.com/vite-plugin/vite-plugin-commonjs/blob/v0.7.0/src/index.ts#L123-L125
        if (id.includes('node_modules/jssip')) {
          return true;
        }
      },
    }),
```
But now this error has appeared:
<img width="987" alt="Снимок экрана 2024-01-31 в 17 50 19" src="https://github.com/vite-plugin/vite-plugin-commonjs/assets/43568935/2de10fe4-4f95-48f8-93cf-e3d0a9627daf">

Is it possible that I missed something in the settings of this package?

**Comment by yejimeiming** [comment]
Can you provide a minimal reproduction repo?

**Comment by KolissnikBogdan** [comment]
> Can you provide a minimal reproduction repo?

I solved this problem by changing other properties of vite.config
Thank you for your reply
