### ISSUE TITLE
[bug]  transed import part miss brackets, cause undefined error，转换得加个括号

### ISSUE THREAD

**Issue by Bowenn** [vite-plugin/vite-plugin-commonjs#54]
Missing brackets while trans ```require('xxx').xxx``` 
Causes reference error

bug sample:
https://github.com/Bowenn/bugfix-vite-plugin-commonjs/blob/bug-sample/test/fixtures/src/module-exports/microtask.cjs
https://github.com/Bowenn/bugfix-vite-plugin-commonjs/blob/bug-sample/test/fixtures/src/module-exports/macrotask_transed.cjs

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/e435e924-6782-404c-ae4e-58c7bb76d664">

- ❌ `var getOwnPropertyDescriptor = __CJS__import__0__.default || __CJS__import__0__.f`
- ✅ `var getOwnPropertyDescriptor = (__CJS__import__0__.default || __CJS__import__0__).f`

**Comment by Bowenn** [comment]
pull request sent

**Comment by yejimeiming** [comment]
Thanks for you feedback!
